export { default as students, studentRelations } from './students'
export { default as professors, professorRelations } from './professors'
export { default as indexCards } from './indexCards'
export { default as courses, courseRelations } from './courses'
export { default as tests, testRelations } from './tests'
export { default as tasks, taskRelations } from './tasks'
export { default as studentCourses, studentCourseRelations } from './studentCourses'
export { default as taskGrades, taskGradeRelations } from './taskGrades'

export * from './enums'
